### ISSUE TITLE
The implementation of Dylora is very different from Kohya's

### ISSUE THREAD

**Issue by iamwangyabin** [KohakuBlueleaf/LyCORIS#101]
Kohya's Dylora implementation only adjusts the require_grad parameter each step, but still uses the full lora tensor (up@down) for computation. I think there may be an issue with this implementation. Does this difference affect performance?

**Comment by KohakuBlueleaf** [comment]
> Kohya's Dylora implementation only adjusts the require_grad parameter each step, but still uses the full lora tensor (up@down) for computation. I think there may be an issue with this implementation. Does this difference affect performance?

Plz check the paper
You should not use full parameter for computation in training 

Id you want to update row n, you should only use row 0~n for computation
