### ISSUE TITLE
Unable to load existing network weights(loha or locon)

### ISSUE THREAD

**Issue by alienedward** [KohakuBlueleaf/LyCORIS#104]
when load the network weights, display as “none",version is "1.9.0.dev13"

![_LIMMMF8C)NFW42NP)WY8X](https://github.com/KohakuBlueleaf/LyCORIS/assets/145338720/792116ec-e667-42b8-ab8b-7c1edfacbade)

**Comment by KohakuBlueleaf** [comment]
plz check previous issue
this feature is missing and will be added in 1.9.0
You can try `pip install -U --pre lycoris-lora` to install the dev version. It should work

**Comment by KohakuBlueleaf** [comment]
This issue should be solved by version 1.9.0
plz check if it works

Will close this in weekend if no reply

**Comment by DevArqSangoi** [comment]
Huh, I was using that option and it seemed to be working just fine. I even tracked down the function to make sure the weights were being loaded. That 'None' was simply because the load weights function didn't have a return.
