### ISSUE TITLE
full module on SDXL?

### ISSUE THREAD

**Issue by tanuki-create** [KohakuBlueleaf/LyCORIS#118]
Is it possible to use full module on SDXL? I am using sd-script but I could not train.

**Comment by KohakuBlueleaf** [comment]
you should be able to run full-module on SDXL
BUT full-module with preset=full will take "more vram" then training sdxl natively.
If what you met is OOM error. That is expected

**Comment by tanuki-create** [comment]
Thank you for your answer. I appreciate you.
