### ISSUE TITLE
Weights are always zero in diag-oft when "constrain=0"

### ISSUE THREAD

**Issue by v0xie** [KohakuBlueleaf/LyCORIS#124]
Sorry for the issue spam ~

When training diag-oft with "constrain=0", `w = self.make_weight(scale, x.device)` in `forward(self, x)` always returns a zero tensor, even after 500+ steps.

It appears to be working with "constrain=1".

```
>>> w.any()
tensor(False, device='cuda:0')
>>> w.mean()
tensor(0., device='cuda:0', dtype=torch.float16)
>>> w.max()
tensor(0., device='cuda:0', dtype=torch.float16)
>>> w.min()
tensor(0., device='cuda:0', dtype=torch.float16)
```

**Comment by KohakuBlueleaf** [comment]
Do you have rescale enabled?
It should work with rescale=False

**Comment by KohakuBlueleaf** [comment]
Rescale=True looks like have problems

**Comment by KohakuBlueleaf** [comment]
Have checked
my "R" have init value to zero which means the real R formulation should be (R+I)WX instead of RWX
you may want to check if kohya also have this problem.
Haven't checked it carefully.

**Comment by KohakuBlueleaf** [comment]
Should be fixed in latest commit

**Comment by v0xie** [comment]
Thank you!
