### ISSUE TITLE
Question: Is it possible to resize a Full Fine-Tuning LoRA

### ISSUE THREAD

**Issue by bmaltais** [KohakuBlueleaf/LyCORIS#133]
I have been testing the Full Fine-Tuning LoRA and tried without success to resize it to a lower rank... do you think it should be possible to resize such a LoRA or it is mathematically impossible?

**Comment by KohakuBlueleaf** [comment]
> I have been testing the Full Fine-Tuning LoRA and tried without success to resize it to a lower rank... do you think it should be possible to resize such a LoRA or it is mathematically impossible?

Just resize it like how you resize lora

Take the weight as the "rebuilt updown" of lora.

It is just diff weight
