### ISSUE TITLE
LoKr factorization seems wrong

### ISSUE THREAD

**Issue by zlstringham** [KohakuBlueleaf/LyCORIS#138]
From https://github.com/KohakuBlueleaf/LyCORIS/blob/c7abd083ad9bc3e18cd3e64b6433eff8525922f6/lycoris/modules/lokr.py#L21C1-L28C84 I see:
```
    factor
        -1               2                4               8               16               ...
    127 -> 1, 127   127 -> 1, 127    127 -> 1, 127   127 -> 1, 127   127 -> 1, 127
    128 -> 8, 16    128 -> 2, 64     128 -> 4, 32    128 -> 8, 16    128 -> 8, 16
    250 -> 10, 25   250 -> 2, 125    250 -> 2, 125   250 -> 5, 50    250 -> 10, 25
    360 -> 8, 45    360 -> 2, 180    360 -> 4, 90    360 -> 8, 45    360 -> 12, 30
    512 -> 16, 32   512 -> 2, 256    512 -> 4, 128   512 -> 8, 64    512 -> 16, 32
    1024 -> 32, 32  1024 -> 2, 512   1024 -> 4, 256  1024 -> 8, 128  1024 -> 16, 64
```

In this case I'm using bmaltais' kohya_ss to create a LoKr for SDXL with `network_dim = conv_dim = network_alpha = conv_alpha = 128`

From the table above, I believe I could assume that for 128, either specifying `-1` or `8` as the factor would produce identical results. However, if I set `factor=-1`, the produced files are ~6MB in size. At `factor=8`, they are ~77MB.

Am I missing something to account for the size difference, or could it be an issue in factorization at `-1`?

Note: I don't see this as a problem with `factorization()` itself, because the logic does produce `8, 16` for both `factorization(128, 8)` and `factorization(128, -1)`. But with the exact same settings, `factor=8` produces substantially larger files than `factor=-1`, which is why I'm confused.]

**Comment by KohakuBlueleaf** [comment]
The factorization do jobs on original module, not your "dim".
