### ISSUE TITLE
Are there any guidelines for inference models?

### ISSUE THREAD

**Issue by laolongboy** [KohakuBlueleaf/LyCORIS#141]
Thanks for your contribution. I used this repository and kohya-ss/sd-scripts to train a Loha model. 

```
network_dim=128
network_alpha=16
network_module="lycoris.kohya"
network_args="algo=loha"
```

Images look good during the training process. I try to inference the model using https://github.com/kohya-ss/sd-scripts/blob/4f93bf10f0f3b84afb7f1670c48eda3dedb4c1d8/sdxl_gen_img.py.

But it seems they are not compatible.

<img width="960" alt="image" src="https://github.com/KohakuBlueleaf/LyCORIS/assets/25175047/9786f29c-3bfc-4178-bd10-b0cada5c5fcd">

**Comment by KohakuBlueleaf** [comment]
LyCORIS haven't supported Kohya's inference scripts yet.
It is planned to be implemented into next version of LyCORIS.

**Comment by KohakuBlueleaf** [comment]
@laolongboy Plz check the latest dev `pip install -U --pre lycoris-lora`.
It should fix this problem
If you have found some bugs with that.
Report here (Or I will close this issue in the weekend)

**Comment by KohakuBlueleaf** [comment]
Assume this been solved.
If it still have problem open new issue
