### ISSUE TITLE
Minor: Suggest Recommending a Python Version or making a minor tweak to enable 3.8

### ISSUE THREAD

**Issue by asutermo** [KohakuBlueleaf/LyCORIS#142]
If I have time I'll add a PR to address this.

If using Python 3.8, you'll run into issues  with 

```
def factorization(dimension: int, factor: int = -1) -> tuple[int, int]:
``` 

This shows in lokr.py line 10.

To work around, for Python 3.8, you could use

```
import math

import torch
import torch.nn as nn
import torch.nn.functional as F

from .base import ModuleCustomSD

from typing import Tuple

def factorization(dimension: int, factor: int = -1) -> Tuple[int, int]:
```

Where the new changes are the typing import and the change from tuple to Tuple.

**Comment by asutermo** [comment]
Additionally in norms.py and full.py, you'll get

```
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

on lines 86 and 110 respectively. This is supported in 3.9 but not 3.8 so seems min recommended python version is 3.9?

**Comment by KohakuBlueleaf** [comment]
The recommended python version is 3.10 (Since even colab have 3.10 now)
This info will be added soon

If you have tested the 3.9 can support it
I can change the min recommended version to 3.9

**Comment by asutermo** [comment]
Oh perfect! I was able to use python 3.8 successfully after the changes above. I imagine 3.9 will work too (may test tomorrow).

I'll be updating soon, I was just mostly being lazy and wasn't sure what the recommended version was).

**Comment by KohakuBlueleaf** [comment]
@asutermo  If you think this is important you can open a PR to dev branch for this.
Remember to put `from typing import ...` on the top of each file.
(above all the other import)

**Comment by KohakuBlueleaf** [comment]
Will accept old python version adaptation code PR
but I will not implement it by myself.
I will close this issue and feel free to open PR
