### ISSUE TITLE
关于OFT的diagonal blocks的数目的疑问

### ISSUE THREAD

**Issue by ziyaxuanyi** [KohakuBlueleaf/LyCORIS#143]
注意到LyCORIS的OFT实现中，diagonal blocks的数目是调用了.lokr中factorization函数计算得出的，计算结果由传入的网络输出out_dim和定义的lora_dim决定。这表明diagonal blocks的数目会因为网络自身的输出out_dim和定义的lora_dim不同而会产生不同的值

注意到OFT的论文中diagonal blocks的数目，经由实现得出，r=4是一个可以同时兼顾参数效率和灵活性的取值。

那么LyCORIS的实现，让不同的网络层有不同的diagonal blocks数目的目的或者好处是什么呢？如果我想让所有的网络层的diagonal blocks数目都像论文中所述的取值为4，应该怎么做呢，除了直接修改代码之外，有没有更优雅的方法呢？

**Comment by KohakuBlueleaf** [comment]
> 注意到LyCORIS的OFT实现中，diagonal blocks的数目是调用了.lokr中factorization函数计算得出的，计算结果由传入的网络输出out_dim和定义的lora_dim决定。这表明diagonal blocks的数目会因为网络自身的输出out_dim和定义的lora_dim不同而会产生不同的值
> 
> 注意到OFT的论文中diagonal blocks的数目，经由实现得出，r=4是一个可以同时兼顾参数效率和灵活性的取值。
> 
> 那么LyCORIS的实现，让不同的网络层有不同的diagonal blocks数目的目的或者好处是什么呢？如果我想让所有的网络层的diagonal blocks数目都像论文中所述的取值为4，应该怎么做呢，除了直接修改代码之外，有没有更优雅的方法呢？

1, 我只是覺得這樣寫比較符合直覺, 我反過來問你為什麼覺得原論文那樣每層有不一樣的block size比較合理。
2, 我可以考慮往config系統加上一些基於層屬性的檢查器。另外就是讓block dim跟block num都可被設定，你想用哪個為主都行。

**Comment by KohakuBlueleaf** [comment]
最後
在github上請用英文。

**Comment by ziyaxuanyi** [comment]
thanks a lot for your answer.
by the way, as mentioned in the paper, for convolutional layers, the number of diagonal blocks should be consistent with the number of channels in the convolutional layer, which can be interpreted as channel sharing.
