### ISSUE TITLE
Error extracting LyCORIS via kohya_ss

### ISSUE THREAD

**Issue by physeo** [KohakuBlueleaf/LyCORIS#150]
Been getting this error for the last month or so when attempting to extract a LyCORIS:

`UNet2DConditionModel: 64, 8, 768, False, False loading u-net: <All keys matched successfully> loading vae: <All keys matched successfully> loading text encoder: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids']) UNet2DConditionModel: 64, 8, 768, False, False loading u-net: <All keys matched successfully> loading vae: <All keys matched successfully> loading text encoder: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids']) Traceback (most recent call last): File "H:\StableDiffusion\kohya_ss\tools\lycoris_locon_extract.py", line 190, in <module> main() File "H:\StableDiffusion\kohya_ss\tools\lycoris_locon_extract.py", line 169, in main state_dict = extract_diff( File "H:\StableDiffusion\kohya_ss\venv\lib\site-packages\lycoris\utils\__init__.py", line 376, in extract_diff for idx, te1, te2 in enumerate(zip(base_tes, db_tes)): ValueError: not enough values to unpack (expected 3, got 2) 23:52:28-452085 INFO     Done extracting...`

Link to [original issue](https://github.com/bmaltais/kohya_ss/issues/1968#issuecomment-1949374287)

**Comment by KohakuBlueleaf** [comment]
duplicate issue. #146
