### ISSUE TITLE
DiagOFTModule requires einops package

### ISSUE THREAD

**Issue by rockerBOO** [KohakuBlueleaf/LyCORIS#154]
Installing lycoris-lora module and a file with `from lycoris import DiagOFTModule` errors about missing `einops` package. Additionally requires `toml` module (but maybe more generally than just DiagOFTModule).

I was doing some independent testing and wanted to mention this. Thank you.

**Comment by KohakuBlueleaf** [comment]
Thx

**Comment by KohakuBlueleaf** [comment]
Added in dev
