### ISSUE TITLE
Can we expect DyLoKr to be available lately?

### ISSUE THREAD

**Issue by suede299** [KohakuBlueleaf/LyCORIS#158]
Does it make training parameter tuning less complicated?

**Comment by KohakuBlueleaf** [comment]
If you are expecting Dynamic factor: no


But I will recommend you to always set your dim to a Very large number like 999999 so lokr will always use "full matrix mode"


In this mode, you only need to tune "factor" (larger = smaller)


And dim/alpha will be ignored
