### ISSUE TITLE
Dataset and Evaluation Metrics

### ISSUE THREAD

**Issue by mikasaq** [KohakuBlueleaf/LyCORIS#159]
Hi, thanks for your great work. Could you upload the dataset used in the paper? And could you provide the codes for evaluation metrics? I think providing those will help the development of the community.

**Comment by KohakuBlueleaf** [comment]
https://huggingface.co/Lycolys

**Comment by KohakuBlueleaf** [comment]
https://github.com/cyber-meow/LyCORIS-evaluation

**Comment by mikasaq** [comment]
Thank you very much!
