### ISSUE TITLE
merge.py cannot import lycoris/lycoris.utils

### ISSUE THREAD

**Issue by CCC-anon** [KohakuBlueleaf/LyCORIS#161]
When attempting to use merge.py to merge a Model and a Lycoris together, this error is returned:

```shell
python merge.py --device cpu --weight 1 ../model/model.safetensors ../model/lycoris.safetensors model_plus_lycoris.safetensors
Traceback (most recent call last):
  File "<>/LyCORIS/tools/merge.py", line 49, in <module>
    from lycoris.utils import merge
ModuleNotFoundError: No module named 'lycoris.utils'
``` 
The issue was solved by manually copying utils.py from an old commit: https://github.com/KohakuBlueleaf/LyCORIS/tree/de98030243d2adcd52b3795d6af5a105c27391ef and placing it in the LyCORIS/lycoris folder
Then running:
```shell
pip install einops
pip install toml
``` 
and moving the merge.py script from LyCORIS/tools to LyCORIS for sanity reasons.
Merge script executed successfully on two devices after this procedure.

Didn't audit what happened with the utils.py file over time but it either needs to go back in that folder or the import from the merge.py script needs to be changed to reflect the current structure.

**Comment by KohakuBlueleaf** [comment]
don't cd into tool folder
or you should install lycoris-lora first.
