### ISSUE TITLE
Weight decomposed OFT (DoOFT) ?

### ISSUE THREAD

**Issue by omer-polar** [KohakuBlueleaf/LyCORIS#165]
I found the OFT and DoRA papers quite similar in spirit. They also seem complimentary? OFT could benefit from trainable magnitudes, and DoRA could benefit from full-rank but block-diagonal (layer-wise same) directional changes. Does this make any sense? If so, would you consider implementing it?

**Comment by KohakuBlueleaf** [comment]
OFT itself have the property of what DoRA want to use.

**Comment by KohakuBlueleaf** [comment]
If you just want trainable magnitudes why not use rescale method.
I have implemented it and Diag OFT paper also mentioned it
