### ISSUE TITLE
Broken DoRA support

### ISSUE THREAD

**Issue by arenasys** [KohakuBlueleaf/LyCORIS#168]
Issue mainly with `lycoris.kohya.create_network_from_weights`:
```py
lyco_type, params = get_module(weights_sd, lora_name)
module = make_module(lyco_type, params, lora_name, orig_modules)
```
`get_module` returns with an extra dora parameters: `return "locon", (up, down, mid, alpha, dora_scale)` etc
`make_module` does not account for this: `up, down, mid, alpha = params`, should be `up, down, mid, alpha, _ = params`.
Which causes:
```
File "/home/usr/.local/lib/python3.11/site-packages/lycoris/modules/__init__.py", line 15, in make_module
    up, down, mid, alpha = params
    ^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 4)
````

**Comment by KohakuBlueleaf** [comment]
First, it should not be `up, down, mid, alpha, _ = params`
Second, I fixed it in latest dev
