### ISSUE TITLE
Newer diffusers support

### ISSUE THREAD

**Issue by arenasys** [KohakuBlueleaf/LyCORIS#169]
Diffusers UNET started replacing `torch.nn.Conv2d` with `LoRACompatibleConv` and `torch.nn.Linear` with `LoRACompatibleLinear`.
This can be mitigated by replacing:
```
if org_module.__class__.__name__ == "Conv2d":
WITH
if isinstance(org_module, torch.nn.Conv2d):
```
And accepting additional args in the forward functions:
```
def forward(self, x):
WITH
def forward(self, x, *args, **kwargs):
```

**Comment by KohakuBlueleaf** [comment]
Will deal with this and similar situation.

**Comment by KohakuBlueleaf** [comment]
@arenasys 2.3.0.dev7 should support all of these
