### ISSUE TITLE
Is configuring multiple algorithms in preset toml not supported?

### ISSUE THREAD

**Issue by suede299** [KohakuBlueleaf/LyCORIS#174]
Using kohya_ss for training, when I use both loha & lokr algo in .toml, I can get normal and expected sample images, but when I load the weights file for testing, I can only get obviously wrong images.(used kohya_ss's sdxl_gen_img.py & auto1111 & comfyUI. All are supported versions of dora)
Not getting any error messages.
This does not happen when I use the included Full Preset for loha or lokr training.
![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/85022330/0bc46cbe-924e-4228-b0fa-a8424b8b77e0)

Other Configurations: 
--network_args "preset=config.toml" "full_matrix=True" "rank_dropout=0.1" "module_dropout=0" "use_scalar=True" "decompose_both=False" "rank_dropout_scale=True" "algo=loha" "dora_wd=True" "train_norm=True"

So is it not supported to be configured this way? Or is there a bug in saving the weights file when configured this way, causing everything to be fine with the sample images during training, while the images generated by loading the file on its own are all wrong. (I asked at kohya_ss and the generation of the sample images is different from the general process of generating them during testing)

Version used for testing：2.3.0.dev3   2.3.0.dev5

**Comment by KohakuBlueleaf** [comment]
Try to disable rank dropout or enable rank_dropout_scale
It can cause problem

**Comment by suede299** [comment]
> Try to disable rank dropout or enable rank_dropout_scale It can cause problem

After many rounds of testing. Determined that you can't use rank_dropout to get normal results.
If rank_dropout > 0, you will only get wrong results even if rank_dropout_scale is turned on.
Not sure if dora_wd or multi algo is affected by this.

**Comment by KohakuBlueleaf** [comment]
> > Try to disable rank dropout or enable rank_dropout_scale It can cause problem
> 
> After many rounds of testing. Determined that you can't use rank_dropout to get normal results. If rank_dropout > 0, you will only get wrong results even if rank_dropout_scale is turned on. Not sure if dora_wd or multi algo is affected by this.

Dora wd with rank dropout will cause huge problems

**Comment by suede299** [comment]
> > > Try to disable rank dropout or enable rank_dropout_scale It can cause problem
> > 
> > 
> > After many rounds of testing. Determined that you can't use rank_dropout to get normal results. If rank_dropout > 0, you will only get wrong results even if rank_dropout_scale is turned on. Not sure if dora_wd or multi algo is affected by this.
> 
> Dora wd with rank dropout will cause huge problems

![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/85022330/8bfd1347-8f63-4258-ac37-caa398c2e327)
Luckily rank_dropout isn't that necessary.
Running into problems now though - network_weights can't continue training.

**Comment by KohakuBlueleaf** [comment]
The network_weights continue training problem is already known and fixing
I will close this issue at first.
