### ISSUE TITLE
Merging DoRA into the model produces a black image.

### ISSUE THREAD

**Issue by Layris0** [KohakuBlueleaf/LyCORIS#175]
As far as I have confirmed here, it seems that in SDXL DoRA and DoKr, a black image is generated when merged into the model.

I am not sure if my understanding is correct, but if you look at the code
https://github.com/KohakuBlueleaf/LyCORIS/commit/47922c57e193c3f0a4e7f0fd5bd7cd11845ba60c
is not applied to the merging process to the model.

**Comment by KohakuBlueleaf** [comment]
Plz check the dev branch.
This is resolved problem

**Comment by Layris0** [comment]
Thank you for your quick reply.
I did not check enough. My apologies.
I checked on the dev branch, and for DoKr trained on 2.2.0post3, black images were generated even after merging using the dev branch.
I checked again with the dev branch with a smaller training and it seemed to be fine. Thank you very much.
