### ISSUE TITLE
DoRA recomposition merge

### ISSUE THREAD

**Issue by rockerBOO** [KohakuBlueleaf/LyCORIS#177]
With DoRA there is the additional vectors but in the paper they suggest improving inference performance by merging the DoRA scale back into the original vectors. This would allow for compatibility with non DoRA interfaces as well as improved inference performance. 

I tried to give a stab at this myself but I didn't get too far because I am not sure how the A / B should work with the DoRA scale when not combined together. 

Thank you!

**Comment by KohakuBlueleaf** [comment]
This idea sounds good but need some clarification:

1. The merge back process will result in "different" lora. Since the scale process acquire the original weight which is full rank. not low rank.
2. The result is as same as: merge it back to original model, extract the difference to a LoRA.
3. Only "DoRA" can do that. DoHa and DoKr cannot do that.

**Comment by KohakuBlueleaf** [comment]
For myself.
I don't see any reason to do this seperatedly. (especially you cannot just "merge" it into single lora. you are actually extracting it.)
If anyone want to use any LyCORIS result but other interface not support them.
Just merge than extract.

**Comment by KohakuBlueleaf** [comment]
If you don't know why DoRA scale cannot just be merged back:

```
F(X) = WX
LoRA(F(X)) = WX + BAX = (W+BA)X
W' = W+BA
DoRA(F(X)) = (W'*d/norm(W', dim=1))X
```

Which means the difference between original weight and final weight is not low rank.
```
diff of LoRA(F(X)) -> BA
diff of DoRA(F(X)) -> (d/norm(W', dim=1) - 1) * W + d/norm(W', dim=1) * BA)
RANK(d/norm(W', dim=1) - 1) * W) = RANK(W) = full rank
```

**Comment by rockerBOO** [comment]
Yeah I was running into that issue you are mentioning since it would require it to be full rank like you explaining. 

I am following and that sounds fine. Does merging LyCORIS "DoRA" work with the model merge? I can give it a shot. 

Thank you for consider and explaining. Appreciate you.

**Comment by KohakuBlueleaf** [comment]
> Yeah I was running into that issue you are mentioning since it would require it to be full rank like you explaining.
> 
> I am following and that sounds fine. Does merging LyCORIS "DoRA" work with the model merge? I can give it a shot.
> 
> Thank you for consider and explaining. Appreciate you.

I think the latest dev should work
master branch have some wrong formula
