### ISSUE TITLE
continuing training when dora_wd is enabled remains unfixed.

### ISSUE THREAD

**Issue by suede299** [KohakuBlueleaf/LyCORIS#180]
use --network_weights
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
![320527075-8bfd1347-8f63-4258-ac37-caa398c2e327](https://github.com/KohakuBlueleaf/LyCORIS/assets/85022330/19ffab1e-469e-461a-9082-e68b5d9c2dde)
algo=loha

**Comment by KohakuBlueleaf** [comment]
2.3.0.dev10 should fix this issue
use 
`pip install -U --pre lycoris-lora>=2.3.0.dev10` to install latest dev

**Comment by Zanedname** [comment]
请问青叶佬，2.3.0是目前最新版吗？我也出现了同样的问题

**Comment by Zanedname** [comment]
I am encountering the same issue discussed previously and wanted to confirm if the current solution is indeed to update to the latest version 2.3.0 of lycoris-lora to address this problem? I wish to make sure I'm taking the correct steps to avoid any further unnecessary complications. Thank you for your time and assistance!

**Comment by KohakuBlueleaf** [comment]
> I am encountering the same issue discussed previously and wanted to confirm if the current solution is indeed to update to the latest version 2.3.0 of lycoris-lora to address this problem? I wish to make sure I'm taking the correct steps to avoid any further unnecessary complications. Thank you for your time and assistance!

2.3.0 is now in dev
It is not actual "solution" and need users' confirmation on "if it is working"

**Comment by KohakuBlueleaf** [comment]
Since there is no updates, I will close this issue at first.
Reopen if this is still not resovled
