### ISSUE TITLE
How to determine whether a model is Lora or LyCoris?

### ISSUE THREAD

**Issue by daixiaoluck** [KohakuBlueleaf/LyCORIS#188]
Hello. Basically, I don’t read English AI materials so I am not familiar with terms and expressions of these topics. Hopefully, it won't impact our communication.
I use a Chinese version of WebUI(绘世启动器, whose key creator is 秋葉aaaki). The software doesn’t distinguish between Lora and LyCoris and the ways to use them are the same.
When I am reading [LoRA Block Weight](https://github.com/hako-mikan/sd-webui-lora-block-weight), I realize that I have to know how to determine whether a model is Lora or LyCoris. Users perform different actions as per the model type(Lora or LyCoris). Could anyone teach me, please?

**Comment by KohakuBlueleaf** [comment]
LoRA is subset of LyCORIS 
So your issue is not precise enough.

If you want to ask how to determine if a model generated by kohya-ss/sd-scripts or My repo is using LoRA algorithm 

You just need to check their state dict. If you only get xxx.lora_down/up.weight and xxx.alpha

Than it is LoRA algorithm.

If you see any other key name, than it is not pure/original lora

**Comment by daixiaoluck** [comment]
> So your issue is not precise enough.

[Here](https://github.com/hako-mikan/sd-webui-lora-block-weight?tab=readme-ov-file#weights-setting), "Weights Setting" section, I found 4 tables. For example, Lora is 17 and LyCORIS is 26. That is why I think they are different. I just know LoRA is one type of LyCORIS.

> You just need to check their state dict.

I totally don't know how and even don't know what it is. Looks like state dict is related to Python code but my models are .safetensors files. Plus, I am not a Python programmer or AI programmer. I am only a user of WebUI and amateur of Stable Diffusion.
My original hope is dropping a .safetensors file to somewhere on WebUI then WebUI prints the result.

**Comment by KohakuBlueleaf** [comment]
This is not an issue of this library.
Plz ask other ppl.
