### ISSUE TITLE
DyLoRa issue in loading the weights

### ISSUE THREAD

**Issue by johnMinelli** [KohakuBlueleaf/LyCORIS#190]
Hi, it seems to me that there is a bug in the process of loading the weights of a network using 'dylora' algorithm.
The dylora modules have the `state_dict` function overwritten in the relative class and the it returns 3 parameters per module but calling `.parameters()` i see a lot more parameters (i guess they are coming from the unet) therefore when calling the `load_state_dict` function or either the `load_weights` from the LycorisNetwork wrapper, it fails, as it tries to load the values for all those parameters.

```
LycorisNetwork.apply_preset({"target_name": [".*attn.*"]})
self.lyco = create_lycoris(self.unet, 1.0, linear_dim=args.rank, linear_alpha=args.alpha_rank, algo="dylora")
self.lyco.apply_to()
len(self.lyco.state_dict())  # = 384
len(self.lyco.loras)  # = 128
len(self.lyco.loras[0].state_dict())  # = 3
len([p for p in self.lyco.parameters()])  # = 16384
len([p for p in self.lyco.loras[0].parameters()])  # = 128
```
In case I'm reading correctly the problem, a possible solution could be to override the `torch.nn.Module:load_state_dict()` function in the dylora module.

**Comment by KohakuBlueleaf** [comment]
Already under development for a while
Currently not accepting any issue related to main branch.
