### ISSUE TITLE
Error when trying to merge a extracted Lycoris into a SDXL model.

### ISSUE THREAD

**Issue by Panchovix** [KohakuBlueleaf/LyCORIS#197]
Hi there, thanks for all your work.

Since some dev updates ago and also main, I get some issues related to this.

I did an extract like this:

`py .\extract_locon.py --is_sdxl --safetensors --mode fixed --linear_dim 32--conv_dim 32 'ponyDiffusionV6XL.safetensors' '4th_tail_v0.4.5.safetensors' '4th_tail_v0.4.5_32dim.safetensors' --device cuda`

Which works fine.

But when I try to do this
`
py .\merge.py '2dFishPonyAnimemix_v10.safetensors' '4th_tail_v0.4.5.safetensors_32dim.safetensors' '2dFishPonyAnimemix_v10.4.5-1.0.safetensors' --is_sdxl --device cuda --weight 1.0 --dtype float16`

I get this issue

```
Converting Dtype and Device: 100%|████████████████████████████████████████████████| 2919/2919 [00:07<00:00, 393.84it/s]
Merging lora_te1:   6%|███▊                                                            | 9/152 [00:00<00:01, 96.60it/s]
Traceback (most recent call last):
  File "G:\acc\sd-scripts-cu124\LyCORIS\tools\merge.py", line 128, in <module>
    main()
  File "G:\acc\sd-scripts-cu124\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\acc\sd-scripts-cu124\LyCORIS\tools\merge.py", line 96, in main
    merge(base_tes, base_unet, lyco, ARGS.weight, ARGS.device)
  File "G:\acc\sd-scripts-cu124\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\acc\sd-scripts-cu124\venv\Lib\site-packages\lycoris\utils\__init__.py", line 470, in merge
    merge_state_dict(
  File "G:\acc\sd-scripts-cu124\venv\Lib\site-packages\lycoris\utils\__init__.py", line 447, in merge_state_dict
    module.merge_to(scale)
  File "G:\acc\sd-scripts-cu124\venv\Lib\site-packages\lycoris\modules\base.py", line 270, in merge_to
    multiplier, self.org_weight.shape, self.org_weight.device
                ^^^^^^^^^^^^^^^
  File "G:\acc\sd-scripts-cu124\venv\Lib\site-packages\torch\nn\modules\module.py", line 1893, in __getattr__
    raise AttributeError(
AttributeError: 'FullModule' object has no attribute 'org_weight'. Did you mean: 'make_weight'?
```

Going back to https://github.com/KohakuBlueleaf/LyCORIS/commit/fc55563 makes it work as expected.

```
Converting Dtype and Device: 100%|███████████████████████████████████████████████| 2919/2919 [00:02<00:00, 1338.03it/s]
Merging lora_te1: 100%|████████████████████████████████████████████████████████████| 152/152 [00:00<00:00, 1157.46it/s]
Merging lora_te2: 100%|███████████████████████████████████████████████████████████| 393/393 [00:00<00:00, 11255.30it/s]
Merging lora_unet: 100%|█████████████████████████████████████████████████████████| 1877/1877 [00:00<00:00, 7420.52it/s]
Unused state dict key: {}
1053 Modules been merged
```

**Comment by KohakuBlueleaf** [comment]
Use latest dev branch

**Comment by Panchovix** [comment]
I'm on latest dev branch

https://github.com/KohakuBlueleaf/LyCORIS/commit/1393a1d

```
PS G:\acc\sd-scripts-cu124\LyCORIS> git log --pretty=format:'%h' -n 1
1393a1d
```

**Comment by KohakuBlueleaf** [comment]
Have you ensured the lycoris in venv is also in latest dev?

**Comment by KohakuBlueleaf** [comment]
I pushed a possible fix and rerun test on my side, it works as expected both before fix and after fix though...

**Comment by Panchovix** [comment]
After the update it works fine now (on torch+cu118 or torch+cu121), seems with torch+cu124 it gives the same issue.

But before the latest commits I had the same issue on the older cuda versions.

Thanks!

**Comment by KohakuBlueleaf** [comment]
> After the update it works fine now (on torch+cu118 or torch+cu121), seems with torch+cu124 it gives the same issue.
> 
> But before the latest commits I had the same issue on the older cuda versions.
> 
> Thanks!

Noted, torch 2.4 may modify some api in nn.Module which affects my custom property
