### ISSUE TITLE
about image generation speed 

### ISSUE THREAD

**Issue by noriwaru** [KohakuBlueleaf/LyCORIS#21]
loha's image generation speed is much slower than lora's, right? Is it just me?
Can you do something about it?

**Comment by KohakuBlueleaf** [comment]
it is normal,
and if you use high dim, the slow down will be more siginificant.

I can do something about it by writing more hook on built-in lora
but this improvement will not take any effect on other lora extension

**Comment by KohakuBlueleaf** [comment]
And this issue is for the extension, not here.

**Comment by noriwaru** [comment]
I see, thank you. My apologies.
