### ISSUE TITLE
"weight´s shape is different:" message when trying to use LoCon

### ISSUE THREAD

**Issue by Darkflo264** [KohakuBlueleaf/LyCORIS#22]
Hi all!
A question to all which have extracted LoCons already:
I am able to extract the difference between the trained and base model as LoRa without problems and it´s working as intended.
When i am trying to extract it (same models) as LoCon, extraction is working well. But when i am trying to use it i am receiving a "weight's shape is different: lora_unet_input_blocks_1_0_in_layers_2.lora_down.weight expected torch.Size([80, 320, 3, 3]) found torch.Size([80, 320]). SD version may be different" error.

So my main question is,  how do i know and / or figure out, which dimensions and settings i have to use when extracting the weights as LoCon?

**Comment by KohakuBlueleaf** [comment]
It looks like you are using old version extension
Please check if you are using latest version
If yes
I will try to figure it out

**Comment by KohakuBlueleaf** [comment]
@Darkflo264 You should install my extension, not this repo XD
https://github.com/KohakuBlueleaf/a1111-sd-webui-locon

**Comment by KohakuBlueleaf** [comment]
And loha/locon with cp-decopmosition is not supported for addnet yet

**Comment by Darkflo264** [comment]
![image](https://user-images.githubusercontent.com/114169154/225338900-ac84d75e-ced7-4fb5-9440-50dd5fec550e.png)

![image](https://user-images.githubusercontent.com/114169154/225339107-561d360c-2296-4b35-aae5-c3d9e85e671f.png)

**Comment by KohakuBlueleaf** [comment]
This is locon with cp decomposition.
By default, locon in new versino is using cp decomposition

**Comment by KohakuBlueleaf** [comment]
I will try to figure out this problem

**Comment by Darkflo264** [comment]
You are awesome!

Thanks. As i mentioned before, i am absolutely not deep into that materies.
To be honest, i dont even know the difference between a locon with and without cp decomposition...

After you have mentioned the default-setting, i have used the --disable_cp parameter, and it´s working as intended right now.

Any source where i can read about the differences of with and without cp decomposition?

**Comment by KohakuBlueleaf** [comment]
@Darkflo264 please check the Algo.md

**Comment by IdiotSandwichTheThird** [comment]
@KohakuBlueleaf 
trying to use the merge.py from this repo gives me the same error when merging a loha with cp decomposition.
```
100%|███████████████████████████████████████████████████████████████████████████████| 152/152 [00:00<00:00, 298.81it/s]
 10%|███████▊                                                                        | 69/709 [00:00<00:04, 129.66it/s]
Traceback (most recent call last):
  File "F:\ezLora\LoRA_Easy_Training_Scripts\LyCORIS\tools\merge.py", line 104, in <module>
    main()
  File "F:\ezLora\LoRA_Easy_Training_Scripts\LyCORIS\tools\merge.py", line 81, in main
    merge_loha(
  File "F:\ezLora\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\lycoris\utils.py", line 444, in merge_loha
    merge(
  File "F:\ezLora\LoRA_Easy_Training_Scripts\sd_scripts\venv\lib\site-packages\lycoris\utils.py", line 428, in merge
    delta = (w1a @ w1b) * (w2a @ w2b)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x320 and 32x320)
```

**Comment by KohakuBlueleaf** [comment]
Yeah the merge.py is outdated and I need sometime to update it(

**Comment by IdiotSandwichTheThird** [comment]
> Yeah the merge.py is outdated and I need sometime to update it(

So it's impossible to use a model trained with this enhancement? Or is there another way of using these that I'm unaware of?

**Comment by KohakuBlueleaf** [comment]
@IdiotSandwichTheThird If your loha model is trained for some sd2 model.
You need to wait me to update merge.py(
