### ISSUE TITLE
Is there a script to merge two LyCORIS?

### ISSUE THREAD

**Issue by silvermoong** [KohakuBlueleaf/LyCORIS#229]
Hi! Is there a script available to merge two LyCORIS? The SuperMerge extension doesn't work for merging two LyCORIS (lokr), and the merge script under tools only supports merging LyCORIS into checkpoints.

**Comment by KohakuBlueleaf** [comment]
If your "two LyCORIS" have exactly same settings than you can even use something like sd_mecha to merge it
if your "two LyCORIS" have different settings than you should merge each into base than merge the two merged models.

**Comment by silvermoong** [comment]
> If your "two LyCORIS" have exactly same settings than you can even use something like sd_mecha to merge it if your "two LyCORIS" have different settings than you should merge each into base than merge the two merged models.

Thanks! Do you happen to have a sd_mecha code example of merging two LyCORIS with same settings? I didn't find an example from the sd_mecha's README or examples.

**Comment by KohakuBlueleaf** [comment]
No
But the LyCORIS model file is just state dict.
You don't need any "special" example for it.

**Comment by silvermoong** [comment]
> No But the LyCORIS model file is just state dict. You don't need any "special" example for it.

Thanks! I check with sd_mecha repo.
