### ISSUE TITLE
overtrains too fast  and not stylisable with same settings as regular lora

### ISSUE THREAD

**Issue by 2blackbar** [KohakuBlueleaf/LyCORIS#24]
was this made just for anime ?
Also this doesnt train higher res as good as regular lora, i think its just a step backwards and new layer of confusion instead of improvement, if it improves its such small percentage its not worth 2xtimes the filesize

**Comment by KohakuBlueleaf** [comment]
First, this is a project with multiple algos, I am not sure What exactly you are talking about. But I guess you are talking about LoCon.

Second, you are not supposed to finetune model for concept with not original resolution (like, 512x512 for SD1.4)

Third, we don't provide any warranty on the model quality.

Finally, If you think this is bad, just don't use it.

P.S. overtrain too fast actually means this method is better at learning thing.
