### ISSUE TITLE
please make cp-decomposition optional

### ISSUE THREAD

**Issue by azumukupoe** [KohakuBlueleaf/LyCORIS#25]
I rolled back to 0.0.9 so that I can train without it and the results are like night and day
turns out I was never wrong about cp-decomposition breaking training for me
but maybe it's because I'm trying to train styles rather than characters?

**Comment by KohakuBlueleaf** [comment]
I have added an option for cp decomposition in network module but forget to add it in to network args XD
wait me a min

**Comment by KohakuBlueleaf** [comment]
oh wait, cp decomposition is already been optional
add "disable_cp=1" to network args can disable cp decomposition for locon or loha
will add this into readme
