### ISSUE TITLE
modules.devices.NansException

### ISSUE THREAD

**Issue by azumukupoe** [KohakuBlueleaf/LyCORIS#27]
getting this error trying to generate using locon trained with 0.1.2

`modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.`

also, file size of safetensors are smaller compared to 0.0.9 (180 MB vs 230 MB)

I have cp-decomposition disabled
`--network_args "conv_dim=64" "conv_alpha=1" "disable_cp=true" "algo=lora"`

**Comment by KohakuBlueleaf** [comment]
This can be caused by:

lora weight too high
CFG too high
Combine too much LoRA
Loss become NaN when training

And is not a bug about LyCORIS.
About the file size, Just check cp-drcomposition part in the algo.md

**Comment by KohakuBlueleaf** [comment]
@azumukupoe "I don't know what is your problem"
I cannot get any information about your problem.

**Comment by KohakuBlueleaf** [comment]
@azumukupoe this 2 version both can work normally
and there are tons of possibilities to make NaN appear.
I cannot even tell if this is my extension/module's problem

**Comment by KohakuBlueleaf** [comment]
If you cannot give me more information about all the extensions you are using, the prompt you use, the lora weight you use, the lora model you use, the training script you use. I cannot give you any support.
I'm not spirit medium
