### ISSUE TITLE
Request: extract_locon.py Half Precision when loading models for memory saving

### ISSUE THREAD

**Issue by torridgristle** [KohakuBlueleaf/LyCORIS#30]
Currently I can't load two models on a free Colab instance, but if I modify it to load the models in half precision it'll work without issue as long as the weights are changed back to float for SVD.

It also seems to load the VAE for both, which shouldn't be needed, and it always loads the text encoder. I'd like an option to skip the text encoder and just focus on the U-Net.

**Comment by KohakuBlueleaf** [comment]
Ok
I will ad these things

**Comment by nanaj96** [comment]
can we possibly extract lycoris from sdxl model? I'm trying but I have gotten the error

**Comment by KohakuBlueleaf** [comment]
> can we possibly extract lycoris from sdxl model? I'm trying but I have gotten the error, does lycoris not support sdxl model yet for this thing?

Other ppl already opened issues for it. and it is added in latest dev.

**Comment by KohakuBlueleaf** [comment]
Have checked if your ckpt file is half-precision it will use half-precision directly
You can consider to convert your ckpt file at first
