### ISSUE TITLE
merge locon to checkpoint

### ISSUE THREAD

**Issue by YinnVI** [KohakuBlueleaf/LyCORIS#33]
is there a tutorial or guide to merge locon into checkpoint?

**Comment by KohakuBlueleaf** [comment]
We are planning to do some tutorial for these things

**Comment by wasongshujun** [comment]
Wonderful, cannot wait to give it a try

**Comment by KohakuBlueleaf** [comment]
I need to support merge for all kind of my model first XD
before making the tutorial
