### ISSUE TITLE
Request: set default value of disable_conv_cp to True for better backward capatibility

### ISSUE THREAD

**Issue by OliverCWY** [KohakuBlueleaf/LyCORIS#35]
Hi, I just upgraded to lycoris 0.1.3 today and tried to fix my training parameters until I realised that there has been a new feature and does not go well with addnet. Considering that some may not be aware of this update and train/upload models incompatible with addnet without noting it, do you mind setting the default as to disable this functionality?

**Comment by KohakuBlueleaf** [comment]
actually since new lycoris train more layers than kohya's
even disable the cp decomposition, you cannot use my locon in kohya's addnet ext

**Comment by OliverCWY** [comment]
> actually since new lycoris train more layers than kohya's even disable the cp decomposition, you cannot use my locon in kohya's addnet ext

I tested on ver 0.1.3 via pip and it works well. Is it due to a current commit?

**Comment by KohakuBlueleaf** [comment]
oh yes
the new part are in dev channel (you can use pip install --pre)

**Comment by OliverCWY** [comment]
> oh yes the new part are in dev channel (you can use pip install --pre)

Thanks. I really appreciate your work.
