### ISSUE TITLE
Error: CUBLAS_STATUS_EXECUTION_FAILED when uses loha

### ISSUE THREAD

**Issue by Yuyu0914** [KohakuBlueleaf/LyCORIS#40]
caching latents.
100%|██████████████████████████████████████████████████████████████████████████████████| 83/83 [00:52<00:00,  1.57it/s]
import network module: lycoris.kohya
Using rank adaptation algo: loha
Apply different lora dim for conv layer
Conv Dim: 8, Linear Dim: 64
Use Dropout value: 0.0
Create LyCORIS Module
create LyCORIS for Text Encoder: 72 modules.
Create LyCORIS Module
create LyCORIS for U-Net: 278 modules.
enable LyCORIS for text encoder
enable LyCORIS for U-Net
prepare optimizer, data loader etc.
use Lion optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 4256
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 714
  num epochs / epoch数: 64
  batch size per device / バッチサイズ: 3
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 45398
steps:   0%|                                                                                 | 0/45398 [00:00<?, ?it/s]epoch 1/64
steps:   0%|                                                         | 99/45398 [06:04<46:22:32,  3.69s/it, loss=0.159]Traceback (most recent call last):
  File "H:\gitrepo\kohya_ss\train_network.py", line 699, in <module>
    train(args)
  File "H:\gitrepo\kohya_ss\train_network.py", line 554, in train
    accelerator.backward(loss)
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 1314, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\lycoris\loha.py", line 24, in backward
    grad_w2a = temp @ w2b.T
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
steps:   0%|                                                         | 99/45398 [06:18<48:09:25,  3.83s/it, loss=0.159]
Traceback (most recent call last):
  File "H:\envs\novelai\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\envs\novelai\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\gitrepo\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "H:\gitRepo\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\gitRepo\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=H:/final-prune.ckpt', '--train_data_dir=H:/image429077', '--resolution=1024,1024', '--output_dir=H:/model', '--logging_dir=H:/log', '--network_alpha=1', '--training_comment=Ariah_Lolita_gloariah\\(lora\\)', '--save_model_as=safetensors', '--network_module=lycoris.kohya', '--network_args', 'conv_dim=8', 'conv_alpha=1', 'algo=loha', '--text_encoder_lr=3.8e-4', '--unet_lr=2.8e-05', '--network_dim=64', '--output_name=Lolita_ariah_v1', '--lr_scheduler_num_cycles=8', '--lr_scheduler_power=2', '--learning_rate=0.0001', '--lr_scheduler=cosine_with_restarts', '--train_batch_size=3', '--max_train_steps=45398', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--cache_latents', '--optimizer_type=Lion', '--max_data_loader_n_workers=8', '--max_token_length=225', '--clip_skip=2', '--keep_tokens=4', '--vae_batch_size=2', '--bucket_reso_steps=64', '--shuffle_caption', '--xformers', '--persistent_data_loader_workers', '--bucket_no_upscale', '--noise_offset=0.1']' returned non-zero exit status 1

**Comment by Yuyu0914** [comment]
I'Normal work when I'm in training lora, but loha is out now.
[torch==1.12.1+cu116 torchvision==0.13.1+cu116] and [torch==2.0] both throws an error

**Comment by Yuyu0914** [comment]
lThe following parameters LR I used before:
unet lr 3e-5,3.8e-5,2.8e-5, 1e-4
text encoder lr 3.8e-6,4.8e-6 1e-5

I trained on win10, ram=16GB, swap ram setting = 64GB 
graphics card = Nvidia Gefore RTX 3090 24GB
I use "https://github.com/bmaltais/kohya_ss/"

The position where the training [CUDA error: CUBLAS_STATUS_EXECUTION_FAILED] occurs is about 100step,10000step,15000step,20000step.

**Comment by Yuyu0914** [comment]
My [kohya_ss/](https://github.com/bmaltais/kohya_ss/)" ver is [v21.3.7](https://github.com/bmaltais/kohya_ss/releases/tag/v21.3.7)

**Comment by Yuyu0914** [comment]
@KohakuBlueleaf Thank you for your attention to the question.
The following is my problem reproduction and some guesses.

My Nvidia Video card is 3090 24GB. 
When I use batch_size=2, VRAM used 16.4GB/24.0GB.
I use the GPU cloud rental platform for training, and I will not use the cloud host to do any work during the training.
This error has happened many times in the past three or four days, and besides that, I have used different base **models,** all with the error.
final-prune.ckpt,hash=SHA256: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
CounterfeitV25_25.safetensors=SHA256: a074b8864e31b8681e40db3dfde0005df7b5309fd2a2f592a2caee59e4591cae

In fact, I used to use batch_size 2 and 3 before. Unfortunately, different size_batch both lead to error. (When I start training, VRAM use < 21GB)
I used [Bmaltais' kohya_ss gui version] to train lora. When batch_size=3 and same training set, it successfully completed the task (about 20,000-30,000 steps, network_dim=192)
There are two data sets for my training, and this problem occurs in both. One data set contains 44 pictures, and the other has 133 pictures.

Besides that, I noticed that the loss function is very hard to descend and the network is hard to converge,But someone else around me also had the problem of slow convergence (his loha was working fine)
I'm not sure if this has anything to do with regularization, in past cases where the program crashed, I had regularization weights of default 1, 0.9, 0.5, 0.25, 0.125
Maybe there is a vanishing gradient problem in my LOHA network and the bf16 datatype does not have enough decimal places to represent numbers? But I did not observed any NaN error.

A few hours ago, I redeployed the training script and this time I used
[derrian-distro/LoRA_Easy_Training_Scripts](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts)
The training parameters are the same as before.

I use the same python version(I use anaconda),but different venv.
The pytorch version I used before:
torch==1.12.1+cu116 torchvision==0.13.1+cu116 (bmaltais/kohya_ss default)
torch==2.0.0+cu118 torchvision==0.15.1+cu118 xformers==0.0.17rc482 (triton installed)

As of the time of my reply, the new environment is working fine. 
steps per epoch =1064, batch_size = 2
epoch 1 --> 6 loss: 0.126, 0.119, 0.123, 0.115, 0.121, 0.116


new env:
torch_version = "torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"
xformers = "https://github.com/DDStorage/LoRA_Easy_Training_Scripts/releases/download/torch2.1.0/xformers-0.0.17+c36468d.d20230318-cp310-cp310-win_amd64.whl"

I am curious whether there are differences in the encapsulation implementation of loha by different people.
However, I hope I can locate the problem.

I will continue to update the information when the training is over or error occurs

Tks.

**Comment by Yuyu0914** [comment]
Supplement: The model saved during the past training hardly showed any characteristics of the training set (I trained painting style), when the loha weight increased, the picture became messy.
After I redeployed, 5000 steps can already reflect a certain painting style

**Comment by Yuyu0914** [comment]
I don't get any errors on the new script.

**Comment by KohakuBlueleaf** [comment]
Ok!
I will close this issue if you don't get any error in this 3~5 days
