### ISSUE TITLE
Is there a way to merge 2 locon loras?

### ISSUE THREAD

**Issue by Raz0rStorm** [KohakuBlueleaf/LyCORIS#41]

**Comment by KohakuBlueleaf** [comment]
Yes, I can make a script for that
but if you want to merge 2 different rank locon/lora
it may be very tricky

**Comment by bmaltais** [comment]
I have done merging 2 different rank locon/lora in the past by resizing both to a common size and then merge them. I guess this could be done dynamically by the script upon detecting the largest of both and resize then merge the smallest with the largest.

**Comment by KohakuBlueleaf** [comment]
@bmaltais Actually you should rebuild them, merge them, and then extract the rebuilt merged wegith in to locon
resize and then merge is not very good (and rebuild/merge/extract can be used to loha and lokr)

**Comment by bmaltais** [comment]
@KohakuBlueleaf This work only if you built the original models, but in the case of merging downloaded models it is not always possible. I agree that the results are not very good... but I was trying to provide a method that I have tried and worked to a point in the past.

**Comment by KohakuBlueleaf** [comment]
@bmaltais You don't need to build the original models
just check their lora_name (lora_name.lora_key)
and then if you meet same lora_name in both state_dict, rebuild their weight and then extract it
not need to build the original models
