### ISSUE TITLE
LoCon LoRA settings formula

### ISSUE THREAD

**Issue by FurkanGozukara** [KohakuBlueleaf/LyCORIS#43]
Can you give some formulas

How many unet rank and text encoder rank we should set?

According to what?

What learning rates we should apply?

![image](https://user-images.githubusercontent.com/19240467/229375078-deb363bb-034b-4179-86ef-4a1966099d15.png)

![image](https://user-images.githubusercontent.com/19240467/229375090-eb9c2c3c-747a-431e-b3bc-8689d215efbf.png)

**Comment by KohakuBlueleaf** [comment]
There is no formula for the settings
all depends on your base model/ what you want to train and your dataset.

But you may want to read this experiment:
https://rentry.org/LyCORIS-experiments
