### ISSUE TITLE
[Question] Can I pull another LoRA algorithm?

### ISSUE THREAD

**Issue by BootsofLagrangian** [KohakuBlueleaf/LyCORIS#45]
I inspired by LoRA and LoHa.

I found some of mathematical method is related with these two. 

I implement this algorithm and it is on experiment.

I have no good VGAs, so can not do benchmark test(e.g. CIFAR-10, CIFAR-100, etc.).

Only I can obtain is very subjective result, images of some characters generated from SD models.

When some test done, can I pull this?

**Comment by KohakuBlueleaf** [comment]
Since I need to make sure your algorithm can be implemented into sd-webui's lora system (with my extension)

After you send the pull request
I may need some time to modify the extension for that algo and make sure the code is fit to my project

But basically just feel free to make PR for it!

**Comment by KohakuBlueleaf** [comment]
@BootsofLagrangian That's great!

**Comment by KohakuBlueleaf** [comment]
I have taken a look for your algo
it looks like it also has some rebuild procedure

In this case you may need to write a custom backward for that rebuild part (just like loha) to avoid super high vram usage (due to torch graph's cache)

**Comment by KohakuBlueleaf** [comment]
@BootsofLagrangian  I think you don't need to restrict the value of factor, since you already have fallback for it.
And you can do something like:
![image](https://user-images.githubusercontent.com/59680068/230530070-49e71c3c-970c-4d1c-93c6-80a9dcd3c5aa.png)


The code I use:
```py
def factorization(dimension: int, factor:int=-1) -> tuple[int, int]:
    if factor > 0 and (dimension % factor) == 0:
        m = factor
        n = dimension // factor
        return m, n
    m, n = 1, dimension
    length = m + n
    while m<n:
        new_m = m + 1
        while dimension%new_m != 0:
            new_m += 1
        new_n = dimension // new_m
        if new_m + new_n > length or new_m>factor:
            break
        else:
            m, n = new_m, new_n
    if m > n:
        n, m = m, n
    return m, n
  ```
  
  And I think you can do something like:
  A matrix: (m, n)
  B matrix: (n, m)
  for example: A[16, 20], B[20, 16]
  
  And you will get smaller result.

**Comment by KohakuBlueleaf** [comment]
And for convolution , I think you can just do something like:

A: [16, 20, 3, 1]
B: [20, 16, 1, 3]
to get kron(A,B) = [320, 320, 3, 3]

And then use cp decomposition (or conventional low rank decomposition) to decopmose them

**Comment by BootsofLagrangian** [comment]
@KohakuBlueleaf 

Thank you for advice!

Before applying custom backward, I need to test this algorithm work fine. 

For now, I found that ,without backward function, this uses same memory as loha

**Comment by KohakuBlueleaf** [comment]
@BootsofLagrangian oh cool, that's good
And for the shape([16, 20], [20, 16]) I think you can continously use your impl, but add more flexible factor (support [5, 64])
And I think for the smaller matrix, you can just use the original size, no need to use low rank representation

like:
A: [5, 5]
B: [64, rank] * [rank, 64]

**Comment by KohakuBlueleaf** [comment]
@BootsofLagrangian https://discord.gg/FUxYWkRe
You can join this discord for more discussion
