### ISSUE TITLE
Will it eventually be possible to extract a LoHA from a checkpoint

### ISSUE THREAD

**Issue by bmaltais** [KohakuBlueleaf/LyCORIS#47]
Do you think it will be possible to extract a LoHA from an existing model at some point?

**Comment by KohakuBlueleaf** [comment]
Impossible

**Comment by KohakuBlueleaf** [comment]
If you want
you can use gradient descent to do this thing.
But the problem is, the finel result basically will be worse than SVD

**Comment by bmaltais** [comment]
Well... There might be a convoluted way... Merge the LoHA with the base checkpoint the extract the resulting model using the lycorix extract script... This should give a pretty good analog.
