### ISSUE TITLE
Resizing LoCons

### ISSUE THREAD

**Issue by lsaa** [KohakuBlueleaf/LyCORIS#5]
is it possible to resize a LoCon like normal nets trained with kohya? 

https://github.com/kohya-ss/sd-scripts/blob/main/networks/resize_lora.py

**Comment by KohakuBlueleaf** [comment]
It is, you can modify kohya's script or wait me for doing that

**Comment by lsaa** [comment]
I'm not very knowledgeable about neural neural nets yet so I'll leave it to you or someone else that wants to try it

**Comment by bmaltais** [comment]
The file has already been modified to do that: https://raw.githubusercontent.com/mgz-dev/sd-scripts/main/networks/resize_lora.py
