### ISSUE TITLE
Examples of Lycoris using methods other than LoCon / LoHa

### ISSUE THREAD

**Issue by hafriedlander** [KohakuBlueleaf/LyCORIS#51]
Hi,

Thanks for these project.

I'm adding Lycoris support to my SD server project, gyre.ai. Do you know of any released Lycoris that use IA3, LoKR (or any of any format that use bias or apply to MultiheadAttention) that I can test compatibility with?

It would be good to have examples of each under a permissive license (Apache 2.0 is good) for cross-testing. They don't have to be _good_, just standardized :).

**Comment by KohakuBlueleaf** [comment]
@hafriedlander If you mean "released LyCORIS for inferencing"
you may want to check my lycoris extension for stable-diffusion-webui here:
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

And for "bias" thing, if what you says is "low rank adaptation with sparse bias". You can check my extension too, and you can use my extraction script to get model with sparse bias (haven't impl it for training).

Stable-Diffusion-Webui itself also support to apply rebuilt weight to MutiheadAttention layer so I think that is a good example for you! (If you need, I can try to write a example for training/using LyCORIS on any torch.nn.Module.)

**Comment by hafriedlander** [comment]
Hi. I've actually based my implementation on that repo. And yes, for inference only. Gyre is diffusers based though (and no web interface, just REST / GRPC), so couldn't use it directly.

(My code is at https://github.com/stablecabal/gyre/blob/test/gyre/pipeline/lycoris.py if you're interested).

I believe I've accurately replicated the loading logic (with the exception of MultiheadAttention), just wanted a way to test it.

I might train up some examples of each to use as a test suite. Will share if I do.
