### ISSUE TITLE
Token/keyword extraction?

### ISSUE THREAD

**Issue by DevArqSangoi** [KohakuBlueleaf/LyCORIS#52]
So, I was wondering if it's possible to create a LyCoris from a keyword/token used in dreambooth training?

For example, if the keyword is 'zwx' and the token is '666', can we extract everything related to 'zwx/666' to create a LyCoris?

Sorry if I'm saying some kind of nonsense, I'm a total amateur in this subject. 😅 

The reason I'm asking is that the extracted LyCoris from my dreambooth training only works with the specific model I used for training.

If I try using another model, the result is garbage and doesn't resemble me at all. I'm not sure if I'm doing something wrong, but I've tried extracting data using all modes (fixed, ratio, quantile, threshold) and with various values.

I'm using TheLastBen dreambooth, and the output model works great, but I just can't seem to create a LyCoris that works with all models.

**Comment by KohakuBlueleaf** [comment]
@DevArqSangoi Basically You are saying kind of nonsense(
The thing is: the method implemented in LyCORIS aren't like TI, TI use additional embed to learn the information of your concept, so you will have seperated tensors for specific concept.

But something like LoRA or DB, you are learning things into the whole model, it is impossible to extract "specific concept" from a whole model.

I know what you think, what you expect and what you want to do. What I can say is "NN doesn't work like that"

**Comment by DevArqSangoi** [comment]
> @DevArqSangoi Basically You are saying kind of nonsense( The thing is: the method implemented in LyCORIS aren't like TI, TI use additional embed to learn the information of your concept, so you will have seperated tensors for specific concept.
> 
> But something like LoRA or DB, you are learning things into the whole model, it is impossible to extract "specific concept" from a whole model.
> 
> I know what you think, what you expect and what you want to do. What I can say is "NN doesn't work like that"

Ops, sorry, forgot to answer, I have ADHD, hehe.

Understood! Thank you very much for the explanation!
