### ISSUE TITLE
Merging to model issue

### ISSUE THREAD

**Issue by JilekJosef** [KohakuBlueleaf/LyCORIS#53]
I tried to merge ia3 to model using the script in tools but is seams that it does not merged corretly, here is comparison.
Standard use
![00029-2813894048](https://user-images.githubusercontent.com/83363948/237052919-3b0acf7c-95be-4a85-b7e3-2bce614baa60.png)
Merge
![00028-2813894048](https://user-images.githubusercontent.com/83363948/237053031-96d97d1d-582f-4b6e-9211-9d58641a3bc9.png)

**Comment by KohakuBlueleaf** [comment]
I will check that!

**Comment by JilekJosef** [comment]
Any updates regarding this. Is it not just possible to use the code from the lycoris extension to merge it the same way? I did some more testing today and when I put weight 1.5 in extension I get quite similar result (same composition) to the merge result aside of the fact that the merge result is brighter a bit melted and some details are different. Or any way how to save merged model directly from lycoris extension?

**Comment by JilekJosef** [comment]
> I put weight 1.5 in extension I get quite similar result (same composition)

Hmm, nevermind it is random there in not actual corelation

**Comment by KohakuBlueleaf** [comment]
Sry I cannot reproduce this issue.
All the code are identical of sd-webui and my impl
I will close this issue
if you think you have found some possible cause
Open a new issue for this
