### ISSUE TITLE
Modification to also support "lora:" in prompt

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [KohakuBlueleaf/LyCORIS#55]
Hello @KohakuBlueleaf, 

I have tried tagging you in this discussion (https://github.com/kohya-ss/sd-scripts/issues/397) but I am not sure if it worked.

The issue: The a1111 built-in lora extension cannot handle newer loras and we were wondering if the lycoris extension could be slightly modified to also work as default lora handler. Please see discussion link for details and add your thoughts there.

**Comment by KohakuBlueleaf** [comment]
@TheOnlyHolyMoly I have replied for this and I can do something like that (you can check the communication between me and vlad)

And this issue actually should be here: https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

I will close this one and you can make a feature request at extension repo
