### ISSUE TITLE
extract_locon Missing key(s) in state dict

### ISSUE THREAD

**Issue by stdkoehler** [KohakuBlueleaf/LyCORIS#62]
I'm trying to use extract_locon on a model trained on v1-5-pruned-emaonly.safetensors

`python tools/extract_locon.py --safetensors --device=cuda --mode="fixed" --linear_dim=64 ~/workspace/python/ai_art/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors ~/workspace/python/ai_art/stable-diffusion/stable-diffusion-webui/models/Stable-diffusion/EmilyKavanaugh/EmilyKavanaugh_3000.safetensors ~/workspace/python/ai_art/stable-diffusion/stable-diffusion-webui/models/LyCORIS/emilyKavanaugh.safetensors`

And receive the following error:

`loading u-net: <All keys matched successfully>
Traceback (most recent call last):
  File "/home/skoehler/workspace/python/ai_art/stable-diffusion/lycoris/tools/extract_locon.py", line 129, in <module>
    main()
  File "/home/skoehler/workspace/python/ai_art/stable-diffusion/lycoris/tools/extract_locon.py", line 97, in main
    base = load_models_from_stable_diffusion_checkpoint(args.is_v2, args.base_model)
  File "/home/skoehler/workspace/python/ai_art/stable-diffusion/lycoris/lycoris/kohya_model_utils.py", line 865, in load_models_from_stable_diffusion_checkpoint
    info = vae.load_state_dict(converted_vae_checkpoint)
  File "/home/skoehler/workspace/python/ai_art/stable-diffusion/lycoris/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.value.weight".`

Is this a bug or am I doing something wrong?

**Comment by KohakuBlueleaf** [comment]
your diffusers version is not fit to kohya sd-scripts

**Comment by stdkoehler** [comment]
Thanks so much for the hint. Can you point me to the version I need to use? I used the requirements.txt in the LyCORIS project to setup my venv. The requirements do not specific versions though.

**Comment by KohakuBlueleaf** [comment]
I will check which version can work
I also meet this problem recently but have no time to dig into it
I only know diffuser update have changed some module name (and then caused this problem

**Comment by KohakuBlueleaf** [comment]
@stdkoehler you may want to try new requirements.txt or just install diffusers==0.10
this should work

**Comment by stdkoehler** [comment]
Thanks that does work! I tested a bit more: It works up to diffusers==0.16.1 for me. However, I did not test if the higher versions might affect quality.
