### ISSUE TITLE
Would LyCORIS support Diffusers Pipeline in future?

### ISSUE THREAD

**Issue by sinri** [KohakuBlueleaf/LyCORIS#65]
Like LoRA we can load its weight into a pipeline class instance to inference, there is not a simple/clear way to go with the LyCORIS cases.
So would LyCORIS support Diffusers Pipeline in future?

**Comment by KohakuBlueleaf** [comment]
@sinri I will try to write a tutorial to use this in diffusers pipeline
since kohya's implementation is based on diffusers' implementation
it is actually quite easy to use that

**Comment by sinri** [comment]
> @sinri I will try to write a tutorial to use this in diffusers pipeline since kohya's implementation is based on diffusers' implementation it is actually quite easy to use that

Thx, waiting for the good news

**Comment by adhikjoshi** [comment]
Also waiting for it

**Comment by KohakuBlueleaf** [comment]
@sinri @adhikjoshi 
You guys should be able to use `lycoris.kohya.create_network_from_weights` with Diffusers' component.
And PEFT library support LoHa and LoKr too.
You may want to check them

**Comment by KohakuBlueleaf** [comment]
@sinri @adhikjoshi LyCORIS is now supporting "ANY" pytorch module!
Check the [example](https://github.com/KohakuBlueleaf/LyCORIS/blob/main/standalone_example.py) for more info!

And also, PEFT is now supporting LoHa and LoKr.
I think this question have been resolved by these 2 things.
