### ISSUE TITLE
Image generation side question 

### ISSUE THREAD

**Issue by a-krum-of-bread** [KohakuBlueleaf/LyCORIS#67]
How should people treat this on the image generation side only I don't find the description clear. Thanks

**Comment by KohakuBlueleaf** [comment]
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by KohakuBlueleaf** [comment]
> Installation is not the problem it's understanding the difference from a regular LoRA when generating an image with the 3 arguments unet, dyn, and te.

te = lyco weight for Text Encoder (CLIP) part, default is 1
unet = lyco weight for unet part, default is as same as te
dyn = the number of rows/cols you want to use with dylora module
