### ISSUE TITLE
[Feature Request] GLoRA - "One-for-All: Generalized LoRA for Parameter-Efficient Fine-tuning"

### ISSUE THREAD

**Issue by dmarx** [KohakuBlueleaf/LyCORIS#68]
I think it would be interesting and useful to implement GLoRA at least as a parameterization of the procedure, even without the evolutionary search piece. It's a generalization over LoRA and several other procedures. People might enjoy the additional flexibility of several additional new methods to play with (VPT, SSF, FacT, AdaptFormer, RepAdaptor...), which GLoRA gives you for free.

* https://sites.google.com/view/generalized-lora
* https://github.com/Arnav0400/ViT-Slim/tree/master/GLoRA
* https://arxiv.org/abs/2306.07967

**Comment by KohakuBlueleaf** [comment]
already working on actually.

**Comment by KohakuBlueleaf** [comment]
the problem is inference

**Comment by KohakuBlueleaf** [comment]
BUT
I think I will implement GLoKr at first, which have more fun to me :P

**Comment by KohakuBlueleaf** [comment]
@dmarx 
![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/59680068/9f3c53c4-da36-4ab7-bea7-f44ec39be364)
actually I already done the glora for a while I just forgot it............
