### ISSUE TITLE
How to find Lora type?

### ISSUE THREAD

**Issue by adhikjoshi** [KohakuBlueleaf/LyCORIS#73]
I have few .safetensors but no way to know which lora model it is,

["LoRA", "LoCon", "LoCon_Lycoris", "LoHa"]

Best way to find lora type?

**Comment by KohakuBlueleaf** [comment]
LoRA and LoCon are all conventional method
Only if you find any xxx.lora_mid in your state dict

LoHA, your state dict will have xxx.hada_xxx

Lokr your state dict will have xxx.lokr_xxx
