### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by adhikjoshi** [KohakuBlueleaf/LyCORIS#75]
Hi,

I am trying for Lycoris Inference using below code, which is not working,

```
import lycoris.kohya as lora
lora_model, weights_sd = lora.create_network_from_weights(
    multiplier, weights_file, vae, [text_model1, text_model2], unet, None, True
)
lora_model.merge_to([text_model1, text_model2], unet, weights_sd, DTYPE, DEVICE)
```

Can you provide code snippet to use Lycoris?

**Comment by KohakuBlueleaf** [comment]
Create network from weights might not working 
I will check

And remember to call the apply_to

**Comment by adhikjoshi** [comment]
> Create network from weights might not working

Yes, its not working, looking for some simple inference snippet.

Will update code for apply_to instead

**Comment by KohakuBlueleaf** [comment]
@adhikjoshi I will check if I have missed something in create_from_weights
and then write a simple snippet for inference in code

**Comment by adhikjoshi** [comment]
Here is snippet which i made so far, but has problems in "apply_to" and not sure if implementation is good.

https://gist.github.com/adhikjoshi/2c6da89cbcd7a6a3344d3081ccd1dda0

**Comment by KohakuBlueleaf** [comment]
@adhikjoshi since lycoris will support different algo for different module

I will write a working version of create network from weights in the future

**Comment by adhikjoshi** [comment]
Yes, this function in utils will give easy inference script.

I did my implementation but layer's aren't calculated well.

**Comment by KohakuBlueleaf** [comment]
lycoris create from weights with different module in same file supported
Will close this issue
