### ISSUE TITLE
 it doesn't seem to work with the sdwebui LyCORIS extension

### ISSUE THREAD

**Issue by zbulrush** [KohakuBlueleaf/LyCORIS#76]
I trained the Loha model using the kohya_ss script, but it doesn't seem to work with the sdwebui-LyCORIS extension. Could it be that it's not supported yet? I've confirmed that sdwebui-LyCORIS is already up-to-date.

**Comment by zbulrush** [comment]
Adding more information: During the training process, the sample images appeared to be normal.

**Comment by KohakuBlueleaf** [comment]
Loha is supported few months ago
It can be some problems between the extension and sdwebui 

Try to update to sdwebui 1.5.0
And use built-in lora to use it
(After 1.5.0 built-in lora will support all lycoris model)

**Comment by zbulrush** [comment]
> 

Sorry, I forgot to mention that I used sdxl.

**Comment by KohakuBlueleaf** [comment]
@zbulrush sdxl should work with built-in lora system
Lycoris ext will deprecated in the future or become a experiment field

Just try latest sd webui and use lycoris model as lora
(You can still use lycoris' arguments system, it is also merged into sd webui now)
