### ISSUE TITLE
ModuleNotFoundError: No module named 'lycoris.kohya_model_utils'

### ISSUE THREAD

**Issue by astro9ine** [KohakuBlueleaf/LyCORIS#77]
I'm trying to extract a Locon from my finetuned model but failed, Traceback (most recent call last):
Traceback (most recent call last):
  File "/workspace/kohya_ss/tools/lycoris_locon_extract.py", line 89, in <module>
    from lycoris.kohya_model_utils import load_models_from_stable_diffusion_checkpoint
ModuleNotFoundError: No module named 'lycoris.kohya_model_utils'

**Comment by KohakuBlueleaf** [comment]
@astro9ine you may need to update your kohya_ss repo
OR
the author may not update for my update.

You should put the issue to kohya_ss repo

**Comment by astro9ine** [comment]
i have seen many people put this issue in kohya ss repo but he says the same thing, he said put the issue in [KohakuBlueleaf] repo

**Comment by KohakuBlueleaf** [comment]
First what I'm talking is "bmaltais/kohya-ss"
Not "kohya-ss/sd-scripts" 
Just to clarify first.

And second.
It is not an issue/bug/problem of my repo
I have changed the Library structure so old import code will break

So the thing is
he need to specify the requirements version or change the import name

**Comment by astro9ine** [comment]
Yea now i understand, like u said he needs to specify the requirements version, because this lycoris extraction is the best thing I've seen, having your 2gb model as 89mb file, Thank u so much

**Comment by KohakuBlueleaf** [comment]
@astro9ine I have updated 1.8.1
and change the import name to 
lycoris.kohya.utils
lycoris.kohya.model_utils

you can consider to notice bmaltais

**Comment by astro9ine** [comment]
Hello man, He updated https://github.com/bmaltais/kohya_ss/commit/d55155e467afe737ea41b1ea49a36edd1b773218
but it still had same error 
and now he changed to 1.8.0
https://github.com/bmaltais/kohya_ss/commit/a3db8cd266f2f9b7da020cc82d779f182aeb28d6
have same issue so far

**Comment by KohakuBlueleaf** [comment]
@astro9ine he updated but never change the import name
that's his issue

**Comment by astro9ine** [comment]
That's messed up Lol, is there a way i can change manually?

**Comment by KohakuBlueleaf** [comment]
@astro9ine I already DM him to change the version and import name
maybe you can wait for it...

**Comment by astro9ine** [comment]
Ofc i can thank you so much
