### ISSUE TITLE
Example of using a script for extraction.

### ISSUE THREAD

**Issue by sashaok123** [KohakuBlueleaf/LyCORIS#8]
We really need an example of using a script for extraction.
I tried to register the same settings as in Kohya, but it doesn't work.

**Comment by neojam** [comment]
just run the "extract_locon.py -h".
It will show you all available options and infos you need.

For fixed mode for example:
python .\LoCon\extract_locon.py --device="cuda" --mode="fixed" --linear_dim=128 --conv_dim=128 "D:\A.cpk" "D:\B.cpk" "D:\Diff.safetensors"

I tired it once a few days ago.
While the extraction went without errors, the extracted LoCon couldn't be used inside the "additional network" webui-extention.
It throws out an error: 
DIFF.safetensors: 'utf-32-be' codec can't decode bytes in position 20-23: code point not in range(0x110000)
Maybe it's fixed already, dont know... Let me know if it works for you
