### ISSUE TITLE
BUG: 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'. 

### ISSUE THREAD

**Issue by HentAIllusiton** [KohakuBlueleaf/LyCORIS#93]
On new installations.
'sd-scripts\venv\Lib\site-packages\torch\nn\functional.py' does not have an attribute named 'scaled_dot_product_attention' ,
instead there is '_scaled_dot_product_attention' 
these error message appears and learning does not start.

Reference document: [https://wikiwiki.jp/sd_toshiaki/%E3%82%A8%E3%83%A9%E3%83%BC%E8%A7%A3%E6%B1%BA%E3%83%A1%E3%83%A2#l611236d](https://wikiwiki.jp/sd_toshiaki/%E3%82%A8%E3%83%A9%E3%83%BC%E8%A7%A3%E6%B1%BA%E3%83%A1%E3%83%A2#l611236d)

>Traceback (most recent call last):
>  File "F:\kohyass20230801\sd-scripts\train_network.py", line 873, in <module>
>    train(args)
>  File "F:\kohyass20230801\sd-scripts\train_network.py", line 178, in train
>    network_module = importlib.import_module(args.network_module)
>  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
>    return _bootstrap._gcd_import(name[level:], package, level)
>  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\lycoris\__init__.py", line 1, in <module>
>    from . import (
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\lycoris\kohya\__init__.py", line 21, in <module>
>    from ..modules.hypernet import ImgWeightGenerator, TextWeightGenerator
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\lycoris\modules\hypernet\__init__.py", line 1, in <module>
>    from .generater import (
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\lycoris\modules\hypernet\generater.py", line 12, in <module>
>    from lycoris.modules.attention import TransformerBlock
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\lycoris\modules\attention.py", line 65, in <module>
>    'torch': getattr(F, 'scaled_dot_product_attention'),
>AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'. Did you mean: '_scaled_dot_product_attention'?
>Traceback (most recent call last):
>  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>    return _run_code(code, main_globals, None,
>  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>    exec(code, run_globals)
>  File "F:\kohyass20230801\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
>    args.func(args)
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
>    simple_launcher(args)
>  File "F:\kohyass20230801\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
>    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by KohakuBlueleaf** [comment]
already fix in dev branch, will fix next stable release

**Comment by KohakuBlueleaf** [comment]
fixed in 1.9.0
