### ISSUE TITLE
Can Loha support block merging operations

### ISSUE THREAD

**Issue by aftermath0703** [KohakuBlueleaf/LyCORIS#95]
I want to merge two Loha with certain block weight parameters, but I don't know how to do it. Currently, it seems that the code only provides the operation of merging Lycoris into checkpoint?
I tried to modify the code based on the implementation of the Lora merge function in the supermerger plugin, but only a single Loha can be implemented to modify the weight of each block. The merging effect of two or more Loha is very poor, it seems that there is a bug when adding weights to each layer. I don't know if this can be fixed.
Looking forward to a reply

**Comment by KohakuBlueleaf** [comment]
You should ask supermerger, not me
I will say all lycoris model "should be able" to be merged with different block weight
