### ISSUE TITLE
LyCORIS Locon error but Kohya Locon works.

### ISSUE THREAD

**Issue by DarkAlchy** [KohakuBlueleaf/LyCORIS#98]
![image](https://github.com/KohakuBlueleaf/LyCORIS/assets/10561690/b03d4dc4-517a-4601-8a72-f8a6b6234bca)
Kohya Locon works with XL, but I have been doing iA3 until I found out ComfyUI will never ever impolement it due to it manipulating the unet and not allow AIT to work.  Therefor I use it for personal now, and went back to try my old locon for public releases to be hit with the above error.

Any ideas?

**Comment by KohakuBlueleaf** [comment]
> ![image](https://user-images.githubusercontent.com/10561690/262513457-b03d4dc4-517a-4601-8a72-f8a6b6234bca.png) Kohya Locon works with XL, but I have been doing iA3 until I found out ComfyUI will never ever impolement it due to it manipulating the unet and not allow AIT to work. Therefor I use it for personal now, and went back to try my old locon for public releases to be hit with the above error.
> 
> Any ideas?

This issue shuold be something in dev branch (pre-release)
You may want to try stable release

**Comment by DarkAlchy** [comment]
Can't do that or I lose iA3.

**Comment by DarkAlchy** [comment]
As long as it doesn't modify the Unet it sounds awesome else it will be DOA for most people due to ComfyUI and AIT.
